

<div data-container="recaptcha">
	
	<script src="<?php echo $this->getScriptUrl(); ?>"></script>
	
	<noscript>
		
		<iframe src="<?php echo $this->getNoscriptUrl(); ?>" height="300" width="500" frameborder="0"></iframe>
		
		<br />
		
		<textarea name="recaptcha_challenge_field" rows="3" cols="40"></textarea>
		<input type="hidden" name="recaptcha_response_field" value="manual_challenge" />
		
	</noscript>
	
</div>
